---
title: "R Notebook"
output: html_notebook
---

Read in and prep data
```{r}
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")


#Assigning Germination plate column
dat$GerminationPlate<-gsub("\\|.*","",dat$Tag)

#Remove maples for the time being.
dat<-dat[!grepl("aple",dat$Tag),]

#Assign family column
prefamily<-gsub("*.\\|","",dat$Tag)
dat$Family<-gsub("\\-.*","",prefamily)


#Assign Leaf number columns
LeafNumber<-gsub(".*\\_","",dat$Sample)
for(i in 1:length(LeafNumber)){
  if(LeafNumber[i]!="1"&LeafNumber[i]!="2"&LeafNumber[i]!="3"){
    LeafNumber[i]<-"pool"
  }
}



dat$LeafNumber<-LeafNumber



```


Glucosinolate and Flavonoid Correlation
```{r}
library(ggplot2)

SlopeCalc<-function(x,y){
  int<-lm(y~x)$coefficients[[1]]
  slope<-lm(y~x)$coefficients[[2]]
  return(c(int,slope))
}
#Remove Pools
dat2<-dat[dat$Pool=="No",]

GFSlopeInt<-SlopeCalc(x=dat2$gluc_Conc,y=dat2$flav_Conc)

ggplot(dat2)+
  geom_point(aes(x=gluc_Conc,y=flav_Conc))+
  geom_abline(aes(slope=GFSlopeInt[2],intercept=GFSlopeInt[1]))


GFSlopeInt

dat
```


Analysis of Leaf number 
```{r}
#Because Chlorphyll does not appear to affect the amount of glucosinolates and flavonoids in the leaves, and the samples appear to be clustered in 2, even after removing the techincal duplicates (within leaf duplicate), I will analyze the variance in glucosinolate and flavonoid against the variance in chlorophyll for those with two samples (from the same plant). If glucosinolates or flavonoids are regulated with chlorophyll, or senesce as chlorophyll does, then as the variation in chlorophyll between samples increases, so should the variation between glucosinolate samples. 


#Looking at those with two samples.. calculate the standard deviation of the secondary compound and chlorophyll data. 

VarAnal<-dat %>% group_by(Tag) %>% summarise_at(vars(ChlorA,ChlorB,gluc_Conc,flav_Conc),.funs=sd)

VarAnal<-VarAnal[!is.na(VarAnal$ChlorA),]

#Interestingly, there is no positive correlation between glucosinolate or flavonoid standard deviation and chlorophyll (A or B) standard deviation in leaf replicates. This indicates that glucosinolates and flavonoids were uninfluenced by the amount of chlorophyll present and may not senesce with chlorophyll. It would appear that defence chemicals are one of the last things to go in the senescence process, if they go at all; however, the over abundance of defence chemicals in apparent senescing leaves may be due to the predator pressure the plants were feeling, so defence chemical regulation remained the same to avoid death before the senescence process could take place. If anything there may be a negative correlation. 

#Glucosinolate, ChlorB
ggplot(VarAnal)+
  geom_point(aes(y=gluc_Conc,x=ChlorB))+
  labs(y="Glucosinolate SD",x="Chlorophyll B SD")

#Flavonoid, ChlorB
ggplot(VarAnal)+
  geom_point(aes(y=flav_Conc,x=ChlorB))+
  labs(y="Flavonoid SD",x="Chlorophyll B SD")

#Glucosinolate, ChlorA
ggplot(VarAnal)+
  geom_point(aes(y=gluc_Conc,x=ChlorA))+
  labs(y="Glucosinolate SD",x="Chlorophyll A SD")

#Flavonoid, ChlorA
ggplot(VarAnal)+
  geom_point(aes(y=flav_Conc,x=ChlorA))+
  labs(y="Flavonoid SD",x="Chlorophyll A SD")


```


```{r}
#On Feb 12, the plate was cleaned with bleach and this removed alot of the staining. This is checking the pools to determine if this cleaning affected the runs. 

boxplot(dat$gluc_Conc[dat$DataFile=="Dat_Feb_13_2020_AM.txt" & dat$Tag=="pool"],dat$gluc_Conc[dat$DataFile!="Dat_Feb_13_2020_AM.txt" & dat$Tag=="pool"])

boxplot(dat$gluc_Conc[dat$DataFile=="Dat_Feb_13_2020_PM.txt" & dat$Tag=="pool"],dat$gluc_Conc[dat$DataFile!="Dat_Feb_13_2020_PM.txt" & dat$Tag=="pool"])

boxplot(dat$gluc_Conc[dat$DataFile=="Dat_Feb_12_2020_PM.txt" & dat$Tag=="pool"],dat$gluc_Conc[dat$DataFile!="Dat_Feb_12_2020_PM.txt" & dat$Tag=="pool"])

#ggplot(dat[dat$Pool=="Yes",])+
#  geom_point(aes(y=gluc_Conc,x=DataFile,colour=DataFile))

#The values seem on the lower end of the pool variation, but it is not overly concerning. No adjustments or removal of data will be made. 

```

```{r}
#Quick look Thrips damage. 
ggplot(dat2)+
  geom_point(aes(y=ThripsDam,x=gluc_Conc))
ggplot(dat2)+
  geom_point(aes(y=ThripsDam,x=flav_Conc))
dat2
#Quick look white fungal damage. 
ggplot(dat2)+
  geom_point(aes(y=WhiteFungDam,x=gluc_Conc))
ggplot(dat2)+
  geom_point(aes(y=WhiteFungDam,x=flav_Conc))

#Quick look black pathogen damage. 
ggplot(dat2)+
  geom_point(aes(y=BlackPathDam,x=gluc_Conc))
ggplot(dat2)+
  geom_point(aes(y=BlackPathDam,x=flav_Conc))

```


