---
title: "Figures"
author: "Richard Honor"
date: "06/05/2020"
output: html_document
---


```{r}
library(dplyr)
source("GGPlot_Themes.R")

#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")

#Remove maple controls data from the data set.
dat<-dat %>% filter(treatment!="mcnt") %>% droplevels()

#Assign family column
prefamily<-gsub("*.\\|","",dat$Tag)
dat$Family<-gsub("\\-.*","",prefamily)

#remove those with fertilizer treatment, and extra genotypes that are only in the alone treatment. 
dat<-dat[!grepl("i",dat$Sample,fixed=T),]

#Initializing columns to avoid constant error messages. 
dat$WhiteFungLogis<-NA
dat$BlackFungLogis<-NA


#Function to weigh pathogen damage by leaf area. 
Weigh<-function(x){
  x/(dat$GM_Leaf_Len*dat$GM_Leaf_Wid)
}
#Function to standardize variables. 
Standardize<-function(x){
  standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
}

#Weighing pathogen damage
dat$BlackPathDamW<-Weigh(dat$BlackPathDam)
dat$ThripsDamW<-Weigh(dat$ThripsDam)

#Standardizing pathogen damage (not white pathogen damage, that is logistic)
dat$ThripsDamW<-Standardize(dat$ThripsDamW)
dat$BlackPathDamW<-Standardize(dat$BlackPathDamW)


#Standardizing pathogen damage (not white pathogen damage, that is logistic)
#dat$ThripsDamW<-Standardize(dat$ThripsDamW)
#dat$BlackPathDamW<-Standardize(dat$BlackPathDamW)

#Summarizing: Taking the mean value of leaves. This tibble contains data at the level of the plant means. 
dat2<-dat %>% group_by(Tag) %>% summarize(ChlorA=mean(ChlorA),ChlorB=mean(ChlorB),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),Family=first(Family),treatment=first(treatment),gh_row=first(gh_row),gh_bench=first(gh_bench),GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),comp_number=first(comp_number),ThripsDam=mean(ThripsDam),WhiteFungDam=mean(WhiteFungDam),BlackPathDam=mean(BlackPathDam),Fern=mean(Fern),gh_col=first(gh_col),BlackPathDamW=mean(BlackPathDamW),ThripsDamW=mean(ThripsDamW))
dat

#All of these genotypes died (15 Genotypes).(We are simply missing a final measurement for e|JBCHY1-1-50|Q|240) That is only 3% Mortality. 
dead<-dat2[is.na(dat2$GM_TotalLeaf_Area),]

#Removing those with dead competitors from the garlic mustard treatment. ("e|JBCHY1-1-50|Q|240") did not die, we are simply missing the final measurement for it.

dead_competitors<-dead %>% filter(treatment=="gm",Tag!="e|JBCHY1-1-50|Q|240") %>% select(comp_number)


dat<-dat %>% filter(!comp_number %in% dead_competitors$comp_number)
dat2<-dat2 %>% filter(!comp_number %in% dead_competitors$comp_number)


```

#Black path pred for alone treatment: 
int: 9571.463
slope: -1006.665

#BlackPath pred for maple treatment: 
int: 8314.753
slope: -1607.188

#Black pred for gm treatment. 
int: 5268.98
slope: -473.91

#Visualizing
```{r}
source("GGPlot_Themes.R")
c<-ggplot(dat2)+
  geom_point(aes(y=GM_TotalLeaf_Area,x=Standardize(ThripsDamW)),colour="black")+theme_simple()+xlab("Thrips Damage")+ylab("Fitness")+
    theme(axis.title.x = element_text(color = "black", size = 16, face = "bold",margin=margin(3,0,3,0)))


a<-ggplot(dat2)+
  geom_point(aes(y=GM_TotalLeaf_Area,x=BlackPathDamW,colour=treatment))+theme_simple_vert()+
  geom_abline(intercept=9571.463,slope=-1006.665,size=1.5,colour="#009E73")+
    geom_abline(intercept=5268.98,slope=-473.91,size=1.5,colour="#56B4E9")+
  geom_abline(intercept=8314.753,slope=-1607.188,size=1.5,colour="#E69F00")+
    scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  scale_x_continuous(expand = c(0,0.1))+
    xlab(bquote(bold("Black Pathogen Damage"~(count/mm^2))))+ylab(bquote(bold("Total Leaf Area"~(mm^2))))

tiff("Selection_Figures/BlackPathogenEffect.tiff", units="in", width=8, height=6, res=300)
a
dev.off()
tiff("Selection_Figures/ThripsEffect.tiff", units="in", width=8, height=6, res=300)
c
dev.off()
```


#Genotype location Figure
```{r}
library(ggplot2)
library("rnaturalearth")
library("rnaturalearthdata")
library("rgeos")
library(dplyr)
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

library("maps")
library("sf")
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE)) #%>% as_tibble()

dat<-read.csv("GenotypeLocation.csv")
Efcc<-dat %>% filter(Family=="EFCC2")
dat2<-dat %>% filter(Family!="EFCC2")




dat<-dat %>% add_row(Family="Common Garden", Latitude=44.5671, Longitude= -76.3250) 

dat$Cat[dat$Family=="Common Garden"]<-"CG"
dat$Cat[dat$Family!="Common Garden"]<-"GM"


minLat<-min(dat2$Latitude)
maxLat<-max(dat2$Latitude)
minLong<-min(dat2$Longitude)
maxLong<-max(dat2$Longitude)

minLatE<-min(Efcc$Latitude)
maxLatE<-max(Efcc$Latitude)
minLongE<-min(Efcc$Longitude)
maxLongE<-max(Efcc$Longitude)

tiff("Other_Figures/Genotype_LocationSimple.tiff", units="in", width=8, height=6, res=300)
ggplot(data=world)+
  geom_sf(colour=gray(.1),fill=gray(0.95))+
  geom_sf(data=states,colour=gray(.1),fill=gray(0.95))+
  geom_point(data=dat,aes(y=Latitude,x=Longitude,colour=Cat, shape=Cat),size=3,stroke=1.25,alpha=0.8)+
  coord_sf(xlim = c(minLong-5, maxLong+5), ylim = c(minLat-5, maxLat+5), expand = F)+
  scale_shape_manual(values=c(4,16))+
  scale_colour_manual(values=c("#E69F00","#009E73"))+
  theme_simple()+
  theme(legend.position = "none",
        axis.line.y.right = element_line(color="black",size=3),
        panel.border = element_rect(colour = "black", fill=NA, size=1)

        )
dev.off()
```


```{r}
library(viridis)
source("GGPlot_Themes.R")
library(cowplot)
world
a<-ggplot(data=world)+
  geom_sf(colour=gray(.3))+
  geom_sf(data=states,colour=gray(.3))+
  geom_point(data=dat,aes(y=Latitude,x=Longitude),size=2.5,stroke=1)+
coord_sf(xlim = c(minLong-4, maxLong+4), ylim = c(minLat-4, maxLat+4), expand = F)+
  scale_shape_manual(values=c(0,1,2,3,4,5,7,8,9,11,12,0,1,2,3,4,5,7,8,9,11,12,4))+theme_simple_vert()

leg<-get_legend(a)
ggplot(data=world)+
  geom_sf(colour=gray(.1),fill=gray(0.95))+
  geom_sf(data=states,colour=gray(.1),fill=gray(0.95))+
  geom_point(data=dat,aes(y=Latitude,x=Longitude),size=1.5,stroke=1.25,colour="darkgreen")+
coord_sf(xlim = c(minLong-5, maxLong+5), ylim = c(minLat-5, maxLat+5), expand = F)+
  scale_shape_manual(values=c(0,1,2,3,4,5,7,8,9,11,12,0,1,2,3,4,5,7,8,9,11,12,4))+theme_simple_multiCol_First()+theme(legend.position = "none")

gray()

b<-ggplot(data=world)+
  geom_sf(colour=gray(.5))+
  geom_sf(data=states,colour=gray(.5))+
  geom_point(data=dat,aes(y=Latitude,x=Longitude),size=2,stroke=1.25)+
coord_sf(xlim = c(minLongE-20, maxLongE+20), ylim = c(minLat-5, maxLat+5), expand = F)+
  scale_shape_manual(values=c(0,1,2,3,4,5,7,8,9,11,12,0,1,2,3,4,5,7,8,9,11,12,4))+theme_simple_multiCol()


a
plots <- align_plots(a, b,align="hv")
plot_grid(a,b,rel_widths = c(1.2,1))

top<-plot_grid(plots[[1]],plots[[2]],ncol=2,rel_widths=c(1,1),rel_heights = c(1,1),labels = c("a","b"),label_fontfamily = "Arial",label_size = 18)
top

tiff("Other_Figures/Genotype_Location.tiff", units="in", width=14, height=6, res=300)
plot_grid(leg,top,ncol=1,rel_heights = c(0.4,1))
dev.off()
library(tidyr)
world %>% tibble()

states %>% tibble()
```




```{r}

c<-c(
110,
27.56,
149.5,
74.31,
208,
30,
193.17,
119,
166.83,
158.97)

sum(c)

owing<-c(
  5,
  2.90/3,
  19.91/3,
  4,
  127.53-5.30*1.15/3,
  5.30*1.15,
  25/3,
  17.27/3,
  9.25,
  58.90,
  25.34,
  7.59/3,
  126.65/3,
  2.22/3,
  14.50/3,
  163.73/3
)

sum(owing)-3*1.15


apr<-c(
  17.25,
  18.11,
  25.8,
  6.9,
  15.53,
  7.5,
  58.9,
  86.05,
  88.03,
  97.84,
  7.59,
  126.65,
  2.22,
  14.5,
  22.02,
  163.73,
  81.4,
  40.25,
  43.82,
  39.62,
  68.99,
  48.02,
  9.19,
  73.02,
  294.75
)

sum(apr)

```



