---
title: "GMatrix"
author: "Richard Honor"
date: "02/06/2020"
output: html_document
---

#Read in and prep data
```{r}
library(ggplot2)
library(lme4)
#library(tidyr)
library(cowplot)
library(grid)
library(gridExtra)
library(dplyr)
source("GGPlot_Themes.R")

#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")

#Remove maple controls data from the data set.
dat<-dat %>% filter(treatment!="mcnt") %>% droplevels()

#remove those with fertilizer treatment, and extra genotypes that are only in the alone treatment. 
dat<-dat[!grepl("i",dat$Sample,fixed=T),]

#Initializing columns to avoid constant error messages. 
dat$WhiteFungLogis<-NA
dat$BlackFungLogis<-NA
```


#Generating data frames with summarized leaf data (dat2) and summarized genotype data (dat3)
```{r}
hist(dat$gluc_Conc)
hist(dat$flav_Conc)
#Both concentrations are above zero. 
min(dat$gluc_Conc,na.rm=T)
min(dat$flav_Conc,na.rm=T)


#Logging data
dat$Fern<-log(dat$Fern+1)
dat$gluc_Conc<-log(dat$gluc_Conc)
dat$flav_Conc<-log(dat$flav_Conc)
dat$ChlorA<-log(dat$ChlorA)
dat$ThripsDam<-log(dat$ThripsDam+1)
dat$BlackPathDam<-log(dat$BlackPathDam+1)



#Creating leaf area vector 
dat$GM_Leaf_Area<-dat$GM_Leaf_Len*dat$GM_Leaf_Wid


#Summarizing: Taking the mean value of leaves. This tibble contains data at the level of the plant means. 
dat2<-dat %>% group_by(Tag) %>% summarize(ChlorA=mean(ChlorA),ChlorB=mean(ChlorB),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),Family=first(Family),treatment=first(treatment),gh_row=first(gh_row),gh_bench=first(gh_bench),GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),comp_number=first(comp_number),ThripsDam=mean(ThripsDam),WhiteFungDam=mean(WhiteFungDam),BlackPathDam=mean(BlackPathDam),Fern=mean(Fern),gh_col=first(gh_col),GM_Leaf_Area=mean(GM_Leaf_Area),Latitude=first(Latitude),Longitude=first(Longitude),Altitude=first(Altitude),RGR1=first(RGR1))
dat

#All of these genotypes died (15 Genotypes).(We are simply missing a final measurement for e|JBCHY1-1-50|Q|240) That is only 3% Mortality. 
dead<-dat2[is.na(dat2$GM_TotalLeaf_Area),]

#Removing those with dead competitors from the garlic mustard treatment. ("e|JBCHY1-1-50|Q|240") did not die, we are simply missing the final measurement for it.

dead_competitors<-dead %>% filter(treatment=="gm",Tag!="e|JBCHY1-1-50|Q|240") %>% select(comp_number)

#Removing those with dead competitors from the analysis. 
dat2<-dat2 %>% filter(!comp_number %in% dead_competitors$comp_number)
dat<-dat %>% filter(!comp_number %in% dead_competitors$comp_number)


##Summarizing: Taking the mean value of plants. This tibble contains data at the level of the family means within each treatment. 
#dat3<-dat2 %>% drop_na(GM_TotalLeaf_Area) %>% group_by(Family,treatment)  %>% summarize_if(is.numeric,mean)



#Because of how zero inflated white pathogen damage is, i will use a logistic regression to model it.
dat2$WhiteFungLogis<-NA
dat2$WhiteFungLogis[dat2$WhiteFungDam==0]<-0
dat2$WhiteFungLogis[dat2$WhiteFungDam>0]<-1


  #Function to standardize variables. 
Standardize<-function(x){
  standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
}

#Standardizing leaf area. 
dat2$GM_Leaf_Area<-Standardize(dat2$GM_Leaf_Area)

```



#Gmatrix model without growth rate
```{r}
library(tidyr)
#library(rms)
library(nlme)

dat2$GM_TotalLeaf_Area<-Standardize(dat2$GM_TotalLeaf_Area)
dat2$flav_Conc<-Standardize(dat2$flav_Conc)
dat2$gluc_Conc<-Standardize(dat2$gluc_Conc)
dat2$ChlorA<-Standardize(dat2$ChlorA)


datG<-dat2 %>% select(Tag,Family,gluc_Conc,ChlorA,flav_Conc,GM_TotalLeaf_Area,gh_bench,treatment) %>%  pivot_longer(c(gluc_Conc,ChlorA,GM_TotalLeaf_Area))

datG$gh_bench<-as.factor(datG$gh_bench)

#---- #Genetic correlation between traits and within treatments
library(glmmTMB)

#Genetic variation for all traits
fit1<-glmmTMB(value ~ name+(1|Family),REML=T,data=datG)
summary(fit1) #Can run seperately for each trait. 

#Genetic correlations between traits. 
fit2<-glmmTMB(value ~ -1+name+(-1+name|Family),REML=T,data=datG)
summary(fit2)
cov2cor(vcov(fit2)$cond)

anova(fit1,fit2)

#Genetic correlations between traits accounting for bench and treatment
fit3<-glmmTMB(value ~ -1+name+gh_bench+treatment +(-1+name|Family),REML=T,data=datG)
summary(fit3) #Took away the effect of treatment on each value (mean effect of treatment). 
anova(fit3,fit1) #This is a much better fit with treatment than both previous models. 

#Genetic correlations between traits accounting for bench and treatment
fit4<-glmmTMB(value ~ -1+name*treatment +gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit4) #Took away the effect of treatment on each value, respective to each value (mean effect of treatment). 
anova(fit4,fit3) #This is a better model than the previous. 

#Genetic correlations between traits accounting for bench and treatment
fit5<-glmmTMB(value ~ -1+name*treatment +gh_bench+name:gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit5) #Took away the effect of treatment on each value, respective to each value (mean effect of treatment). #####This model has interaction with treatment , gh bench and name such that treatment and gh bench have individual effects on each of chlophyll body size, and glucosinolate concentration. Glucosinolate has alot of genetic variation, but it is highly correlated with total leaf area and chlrophyll a. 
anova(fit5,fit4)
#This is the best model yet. GXE effects are ellusive, however.
cov2cor(vcov(fit5)$cond)

#Looking for genetic variation within each treatment (GXE)
fit6<-glmmTMB(value ~ -1+name*gh_bench+treatment+(-1+name|treatment/Family),REML=T,data=datG)
summary(fit6) #Model too complicated to test a GXE for all. 

```

#Generating genetic correlations and H2
```{r}
dat2$GM_TotalLeaf_Area<-Standardize(dat2$GM_TotalLeaf_Area)
dat2$flav_Conc<-Standardize(dat2$flav_Conc)
dat2$gluc_Conc<-Standardize(dat2$gluc_Conc)
dat2$ChlorA<-Standardize(dat2$ChlorA)
dat2$RGR1<-Standardize(dat2$RGR1)
dat2$gh_bench<-as.factor(dat2$gh_bench)

#gluc_Conc,ChlorA,GM_TotalLeaf_Area
datG<-dat2 %>% select(Tag,Family,gluc_Conc,ChlorA,flav_Conc,GM_TotalLeaf_Area,gh_bench,treatment) %>%  pivot_longer(c(gluc_Conc,ChlorA,GM_TotalLeaf_Area))

fit5<-glmmTMB(value ~ -1+name*treatment +gh_bench+name:gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit5)


#flav_Conc,ChlorA #Genetic correlation with other variables are not possible due to reduced sample size. ... it just wont fit. 
datG<-dat2 %>% select(Tag,Family,gluc_Conc,ChlorA,flav_Conc,GM_TotalLeaf_Area,gh_bench,treatment) %>%  pivot_longer(c(flav_Conc,ChlorA))

fit5<-glmmTMB(value ~ -1+name+treatment +gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit5)

```





#Gmatrix model with growth Rate
```{r}
library(tidyr)

#Standardizing variables
dat2$GM_TotalLeaf_Area<-Standardize(dat2$GM_TotalLeaf_Area)
dat2$flav_Conc<-Standardize(dat2$flav_Conc)
dat2$gluc_Conc<-Standardize(dat2$gluc_Conc)
dat2$ChlorA<-Standardize(dat2$ChlorA)
dat2$RGR1<-Standardize(dat2$RGR1)

#Creating data frame
datG<-dat2 %>% select(Tag,Family,gluc_Conc,ChlorA,flav_Conc,GM_TotalLeaf_Area,gh_bench,treatment,RGR1) %>%  pivot_longer(c(ChlorA,GM_TotalLeaf_Area,RGR1))

#Making bench a factor. 
datG$gh_bench<-as.factor(datG$gh_bench)

#---- #Genetic correlation between traits and within treatments
library(glmmTMB)

#Genetic variation for all traits
fit1<-glmmTMB(value ~ name+(1|Family),REML=T,data=datG)
summary(fit1) # 

#Genetic correlations between traits. 
fit2<-glmmTMB(value ~ -1+name+(-1+name|Family),REML=T,data=datG) #Too complicated with growth rate included. even without glucosinolate included. 
summary(fit2)
cov2cor(vcov(fit2)$cond)

anova(fit1,fit2)

#Genetic correlations between traits accounting for bench and treatment
fit3<-glmmTMB(value ~ -1+name+gh_bench+treatment +(-1+name|Family),REML=T,data=datG)
summary(fit3) #Took away the effect of treatment on each value (mean effect of treatment). 
anova(fit3,fit1) #This is a much better fit with treatment than both previous models. 

#Genetic correlations between traits accounting for bench and treatment
fit4<-glmmTMB(value ~ -1+name*treatment +gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit4) #Took away the effect of treatment on each value, respective to each value (mean effect of treatment). 
anova(fit4,fit3) #This is a better model than the previous. 

#Genetic correlations between traits accounting for bench and treatment
fit5<-glmmTMB(value ~ -1+name*treatment +gh_bench+name:gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit5) #Took away the effect of treatment on each value, respective to each value (mean effect of treatment). #####This model has interaction with treatment , gh bench and name such that treatment and gh bench have individual effects on each of chlophyll body size, and glucosinolate concentration. Glucosinolate has alot of genetic variation, but it is highly correlated with total leaf area and chlrophyll a. 
anova(fit5,fit4)
#This is the best model yet. GXE effects are ellusive, however.
cov2cor(vcov(fit5)$cond)

#Looking for genetic variation within each treatment (GXE)
fit6<-glmmTMB(value ~ -1+name*gh_bench+treatment+(-1+name|treatment/Family),REML=T,data=datG)
summary(fit6) #Model too complicated to test a GXE for all. 

```

#Gmatrix with flavonoids included. 
```{r}

dat2$GM_TotalLeaf_Area<-Standardize(dat2$GM_TotalLeaf_Area)
dat2$flav_Conc<-Standardize(dat2$flav_Conc)
dat2$gluc_Conc<-Standardize(dat2$gluc_Conc)
dat2$ChlorA<-Standardize(dat2$ChlorA)


datG<-dat2 %>% select(Tag,Family,gluc_Conc,ChlorA,flav_Conc,GM_TotalLeaf_Area,gh_bench,treatment) %>%  pivot_longer(c(gluc_Conc,flav_Conc,ChlorA,GM_TotalLeaf_Area))

datG$gh_bench<-as.factor(datG$gh_bench)

#---- #Genetic correlation between traits and within treatments
library(glmmTMB)

#Genetic variation for all traits
fit1<-glmmTMB(value ~ name+(1|Family),REML=T,data=datG)
summary(fit1) #Can run seperately for each trait. 

#Genetic correlations between traits.  #This model is too large to fit. not looking good. 
fit2<-glmmTMB(value ~ -1+name+(-1+name|Family),REML=T,data=datG)
summary(fit2)

#Genetic correlations between traits accounting for bench and treatment .. too large to fit
fit3<-glmmTMB(value ~ -1+name+gh_bench+treatment +(-1+name|Family),REML=T,data=datG)


#Genetic correlations between traits accounting for bench and treatment
fit4<-glmmTMB(value ~ -1+name*treatment +gh_bench+(-1+name|Family),REML=T,data=datG)
#Too large to fit.... 

#Genetic correlations between traits accounting for bench and treatment... this model fits though. 
fit5<-glmmTMB(value ~ -1+name*treatment +gh_bench+name:gh_bench+(-1+name|Family),REML=T,data=datG)
summary(fit5) #Took away the effect of treatment on each value, respective to each value (mean effect of treatment). #####This model has interaction with treatment , gh bench and name such that treatment and gh bench have individual effects on each of chlophyll body size, and glucosinolate concentration. Glucosinolate has alot of genetic variation, but it is highly correlated with total leaf area and chlrophyll a. 

```

#Gnetic variation for individual traits
```{r}
#-----
####. CHlorophyll A
dat2$gh_bench<-as.factor(dat2$gh_bench)
fit1<-glmmTMB(ChlorA ~ gh_bench+treatment+GM_Leaf_Area+(1|Family),REML=T,data=dat2)
summary(fit1) 
0.0214/(0.0214+0.89)
#2.3 % of the variation in chlorophyll 

fit2<-glmmTMB(ChlorA ~ gh_bench*treatment+GM_Leaf_Area+(1|Family),REML=T,data=dat2)
summary(fit2) 
anova(fit1,fit2)#Interaction is not significant

fit3<-glmmTMB(ChlorA ~ treatment+(treatment|Family),REML=T,data=dat2) #Tests whethere there is significant genetic covariation amoung treatments.
#Tests GXE for that trait. On the left of the pipe is what the axis are, on the right side of the pipe is what the points are. ... too large. #get genetic variation in each treatment. Genetic correlation betwen treatments (random effect) - 
summary(fit3) #Too large to fit. 


#Glucosinolate
fit1<-glmmTMB(gluc_Conc ~ gh_bench+treatment+GM_Leaf_Area+(1|Family),REML=T,data=dat2)
summary(fit1) 
0.0876/(0.819+0.0876)
#Genotype accounts for 9.6% of glucosinolate variation


fit2<-glmmTMB(gluc_Conc ~ gh_bench*treatment+GM_Leaf_Area+(1|Family),REML=T,data=dat2)
summary(fit2) 
anova(fit1,fit2)#Interaction is not significant

fit3<-glmmTMB(gluc_Conc ~ treatment+(treatment|Family),REML=T,data=dat2) #Tests whethere there is significant genetic covariation amoung treatments.
#Tests GXE for that trait. On the left of the pipe is what the axis are, on the right side of the pipe is what the points are. ... too large. 
summary(fit3) #Too large to fit. 

#Trying model with further nesting 


#RGR1
fit1<-glmmTMB(RGR1 ~ gh_bench+treatment+(1|Family),REML=T,data=dat2)
summary(fit1)

0.0259/(0.828+0.0259) #Genotype explains only 3% of the variation in growth rate. 

#Total size
fit1<-glmmTMB(GM_TotalLeaf_Area ~ gh_bench+treatment+(1|Family),REML=T,data=dat2)
summary(fit1)

0.0097/(0.61+0.0097) #About Genotype explains only 1.5% of the variation in body size.
```



