---
title: "PathogenDefenseAnalysis"
author: "Richard Honor"
date: "03/05/2020"
output: html_document
---

#Read in and prep data
```{r}
library(ggplot2)
library(dplyr)
library("glmmTMB")


#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")

#Assign family column
prefamily<-gsub("*.\\|","",dat$Tag)
dat$Family<-gsub("\\-.*","",prefamily)

#remove those with fertilizer treatment, and extra genotypes that are only in the alone treatment. 
dat<-dat[!grepl("i",dat$Sample,fixed=T),]

#Converting white fung dam to logistic, as the quantitative measurement was unreliable 
dat$WhiteFungLogis<-NA
dat$WhiteFungLogis[dat$WhiteFungDam==0]<-0
dat$WhiteFungLogis[dat$WhiteFungDam>0]<-1

#Function to weigh pathogen damage by leaf area. 
Weigh<-function(x){
  x/(dat$GM_Leaf_Len*dat$GM_Leaf_Wid)
}

Standardize<-function(x){
  standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
}

#Weighing pathogen data.
dat$BlackPathDamW<-Weigh(dat$BlackPathDam)
dat$ThripsDamW<-Weigh(dat$ThripsDam)

#Standardizing pathogen damage (not white pathogen damage, that is logistic)
dat$ThripsDamW<-Standardize(dat$ThripsDamW)
dat$BlackPathDamW<-Standardize(dat$BlackPathDamW)


#Logging pathogen damage data and fern data variables as they are very skewed. 
dat$BlackPathDamW<-log(dat$BlackPathDamW+abs(min(dat$BlackPathDamW,na.rm=T)+1))
dat$ThripsDamW<-log(dat$ThripsDamW+abs(min(dat$ThripsDamW,na.rm=T)+1))

dat$Fern<-log(dat$Fern+1)
dat$gluc_Conc<-log(dat$gluc_Conc)
dat$flav_Conc<-log(dat$flav_Conc)
dat$ChlorA<-log(dat$ChlorA)


#Average Duplicates. 
dat2<-dat %>% select(-X) %>% group_by(Tag) %>%  summarize(gh_col=first(gh_col),gh_bench=first(gh_bench),treatment=first(treatment),GA3=first(GA3),Family=first(Family),Maple_StemHeight_End=mean(Maple_StemHeight_End),Maple_LeafNum_End=mean(Maple_LeafNum_End),maple_leaf_length_0=mean(maple_leaf_length_0),maple_leaves_0=mean(maple_leaves_0),Maple_TotalLeafArea_End=mean(Maple_TotalLeafArea_End),MapleDamage=mean(Maple_Damage_End),Fern=first(Fern),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),maple_height_0=mean(maple_height_0),ChlorA=mean(ChlorA), GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),ThripsDam=mean(ThripsDam),BlackPathDam=mean(BlackPathDam),WhiteFungDam=mean(WhiteFungDam),BlackPathDamW=mean(BlackPathDamW),ThripsDamW=mean(ThripsDamW),WhiteFungLogis=mean(WhiteFungLogis))

#Generating leaf area. 
dat$GM_Leaf_Area<-dat$GM_Leaf_Wid*dat$GM_Leaf_Len
#standardizing Leaf area. 
dat$GM_Leaf_Area<-Standardize(dat$GM_Leaf_Area)
```



#Modelling : Negative binomial on Thrips Damage. 
```{r}
#Because there is no such model that is negative binomial and continuous, i will have to controll for leave size and leaf health in the model. Leaf size must be contorlled for because more pathogens can appear on leaves with larger surface area. 

#Modelling Random Effects


fit_full<-glmmTMB(ThripsDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag)+(1|gh_bench),family=nbinom2,data=dat)
summary(fit_full)

fit_full2<-glmmTMB(ThripsDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family)+(1|gh_bench),family=nbinom2,data=dat)

fit_full3<-glmmTMB(ThripsDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag),family=nbinom2,data=dat)

fit_full4<-glmmTMB(ThripsDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|gh_bench),family=nbinom2,data=dat)

fit_full5<-glmmTMB(ThripsDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Tag)+(1|gh_bench),family=nbinom2,data=dat)


#Is Tag important? 
anova(fit_full,fit_full2) #Yes, 

#Is Family important? 
anova(fit_full,fit_full5) #No, Family is not significant, but Tag is.  
#Is GH_Bench important?

anova(fit_full,fit_full3) #No greenhouse bench is not important. 
#Therefore, Tag is the only random effect i need to include. 


#Modelling fixed effects 
fit_full<-glmmTMB(ThripsDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Tag),family=nbinom2,data=dat)


summary(fit_full) #Including leaf size almost completely eliminates the effect here. However, controlling for chlorophyll brings the significance right back for both. This is interesting. It means that after you controll for the overall health of the plant, glucosinolates and flavonoids significantly reduce thrips abundance.

fit_1<-update(fit_full,~.-treatment)
anova(fit_full,fit_1) #treatment is important. There are much more thrips in the garlic mustard treatment, which makes sense. 

#Could there be a synergistic effect of producing high glucosinolates and flavonoids? 
fit_1<-update(fit_full,~.+ gluc_Conc:flav_Conc)
anova(fit_full,fit_1) #No there isnt. 

summary(fit_full)
plot(resid(fit_full))
plot(resid(fit_full)^2)
#The model appears to be a good fit. 
#Thrips is reduced by both glucosinolates and flavonoids. 
```




#Modelling: Negative Binomial -- BlackPathDam 
```{r}

#Modelling random effects 

fit_full<-glmmTMB(BlackPathDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag)+(1|gh_bench),family=nbinom2,data=dat)

fit_full2<-glmmTMB(BlackPathDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family)+(1|gh_bench),family=nbinom2,data=dat)

fit_full3<-glmmTMB(BlackPathDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag),family=nbinom2,data=dat)

fit_full4<-glmmTMB(BlackPathDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Tag)+(1|gh_bench),family=nbinom2,data=dat)

#Is Tag imporatant? 
anova(fit_full,fit_full2) #Yes it is. 

#Is gh_Bench imporatant? 
anova(fit_full,fit_full3) #No it is not.

#Is Family Important. 
anova(fit_full,fit_full4) #Yes it is 

#Modelling fixed effects 
fit_full<-glmmTMB(BlackPathDam~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag),family=nbinom2,data=dat)

fit1<-update(fit_full,~.-treatment)
anova(fit_full,fit1) #treatment is important


summary(fit_full)# Gluc_Conc is not important. 
#Therefore, the best model is one with flavonoids and treatment. 

fit1<-update(fit_full,~.-gluc_Conc)
summary(fit1)
plot(residuals(fit1))
#All else are significant (except for leaf size), however, it is close to significant, therefor i will leave it in the model.Therefore, flavonoids alone reduces black pathogen abundance -- even after contorlling for leaf allocation. There is likely also less blackpathogen damage in the maple treatment than in the garlic mustard treatment. 

fitnc<-glmmTMB(BlackPathDam~flav_Conc+GM_Leaf_Area+(1|Family/Tag),family=nbinom2,data=dat)
summary(fitnc)

fitc<-glmmTMB(BlackPathDam~flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag),family=nbinom2,data=dat)
summary(fitc)

#The effect and p value actually increases after controlling for chlorophyll. This is odd, but it doesnt appear that they are sharing the same effect. 
```


#Modelling negative binomial White Fungal damage. 


#WhitePathDam -- logistic regression 
```{r}
#Modelling Random Effects
fit_full<-glmmTMB(WhiteFungLogis~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family/Tag)+(1|gh_bench),family=binomial,data=dat)

fit_full2<-glmmTMB(WhiteFungLogis~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family)+(1|gh_bench),family=binomial,data=dat)

fit_full3<-glmmTMB(WhiteFungLogis~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family),family=binomial,data=dat)

fit_full4<-glmmTMB(WhiteFungLogis~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|gh_bench),family=binomial,data=dat)

#Is Tag important? 
anova(fit_full,fit_full2) #no, the individual is not important. 

#Is Family important? 
anova(fit_full2,fit_full4) #Yes, family is important for predicting fungal presence. 

#Is gh_bench important? 
anova(fit_full2,fit_full3) #No, greenhouse bench is not important. 


#Modelling fixed effects. 
fit_full<-glmmTMB(WhiteFungLogis~treatment+gluc_Conc+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family),family=binomial,data=dat)

fit1<-update(fit_full,~.-treatment)
anova(fit_full,fit1) #Treatment is important

summary(fit_full)#glucosinolate concentration is not. 
fit1<-glmmTMB(WhiteFungLogis~treatment+flav_Conc+GM_Leaf_Area+ChlorA+(1|Family),family=binomial,data=dat)

summary(fit1) #ChlorA is not 


fit1<-glmmTMB(WhiteFungLogis~treatment+flav_Conc+GM_Leaf_Area+(1|Family),family=binomial,data=dat)

summary(fit1)#flavonoids is not


fit1<-glmmTMB(WhiteFungLogis~treatment+GM_Leaf_Area+(1|Family),family=binomial,data=dat)
summary(fit1)
#treatment and leaf area all predict whehter or not garlic mustard will be affected by powdery mildue. This suggests that garlic mustard is very poorly defended against such a predator, or there is a plastic response to it. 

```



#Visualization -- black pathogen abundance by flavonoids.
```{r}
#Mininum adequate model for black pathogen abundance
fit<-glmmTMB(BlackPathDam~treatment+flav_Conc+Standardize(GM_Leaf_Area)+Standardize(ChlorA)+(1|Family/Tag),family=nbinom2,data=dat)
summary(fit)
#Using the standardized variables allows me to model the response given the mean chlorophyll and leaf area. 

source("GGPlot_Themes.R")
#Reversing link function, to estimate the data on the response scale. 
flavSlope=function(x,int,log=FALSE){
  if(log==T){
    y=-1.68*x+int
  }
  else{
    y=exp(-1.68*x+int)
  }
  return(y)
}



#Determining predicted values for each treatment along the rang of flavonoid concentration, given chlorophyll and  leaf size are held constant and using the mean of the random effects. 
flavplot=seq(min(dat$flav_Conc,na.rm = T),max(dat$flav_Conc,na.rm=T),length.out = 688)

#Calculating slope values
flavyA<-flavSlope(flavplot, -0.99)
flavyGM<-flavSlope(flavplot, -0.99+0.2519)
flavyM<-flavSlope(flavplot, -0.99-0.43542)


tiff("Defence_Figures/FlavonoidBlackPathogen2.tiff", units="in", width=8, height=6, res=300)
ggplot(dat[!is.na(dat$flav_Conc),])+
  geom_point(aes(y=BlackPathDam,x=flav_Conc,colour=treatment))+
theme_simple()+
  geom_path(x=flavplot,y=flavyA,size=1.5,colour="#009E73")+
    geom_path(x=flavplot,y=flavyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=flavplot,y=flavyM,size=1.5,colour="#E69F00")+

  scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+

  scale_y_continuous(breaks=seq(0,70,5))+
  ylab("Black Pathogen Damage")+
xlab(bquote(bold("[Total Flavonoid] (" ~log(mg/ml)~")")))
dev.off()

#LOG Plot

flavyA<-flavSlope(flavplot, -0.99+1,log = T)
flavyGM<-flavSlope(flavplot, -0.99+0.2519+1,log = T)
flavyM<-flavSlope(flavplot, -0.99-0.43542+1,log = T)



tiff("Defence_Figures/LOG_FlavonoidBlackPathogen.tiff", units="in", width=8, height=6, res=300)
ggplot(dat[!is.na(dat$flav_Conc),])+
  geom_point(aes(y=log(BlackPathDam+1),x=flav_Conc,colour=treatment))+
  geom_path(x=flavplot,y=flavyA,size=1.5,colour="#009E73")+
    geom_path(x=flavplot,y=flavyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=flavplot,y=flavyM,size=1.5,colour="#E69F00")+

  scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+

  #scale_y_continuous(breaks=seq(0,70,5))+
  ylab(bquote(bold(log("Black Pathogen Damage"+1))))+
xlab(bquote(bold("[Total Flavonoid] (" ~log(mg/ml)~")")))+
  theme_simple_vert()
dev.off()

hist(log(dat$BlackPathDam))
log(dat$BlackPathDam)
```


#Visualizing thrips damage before the data were logged
```{r}
fit_full<-glmmTMB(ThripsDam~treatment+flav_Conc+GM_Leaf_Area+ChlorA+(1|Tag),family=nbinom2,data=dat)
summary(fit_full)

fit_full2<-glmmTMB(ThripsDam~treatment+gluc_Conc+GM_Leaf_Area+ChlorA+(1|Tag),family=nbinom2,data=dat)
summary(fit_full2)


source("GGPlot_Themes.R")
#Reversing link function, to estimate the data on the response scale. 
flavSlope=function(x,int){
  y=exp(-2.1879 *x+int+0.7994*mean(dat$GM_Leaf_Area,na.rm=T)+1.8896*mean(dat$ChlorA,na.rm=T))

  return(y)
}

glucSlope=function(x,int){
  y=exp(-2.63639*x+int+0.82475*mean(dat$GM_Leaf_Area,na.rm=T)+1.82279 *mean(dat$ChlorA,na.rm=T))
  
  return(y)
}



#Determining x range to fit the line to 
flavplot=seq(min(dat$flav_Conc,na.rm = T),max(dat$flav_Conc,na.rm=T),length.out = 688)
glucplot=seq(min(dat$gluc_Conc,na.rm = T),max(dat$gluc_Conc,na.rm=T),length.out = 708)

#Calculating predicted values
flavyA<-flavSlope(flavplot, 1.4237)
flavyGM<-flavSlope(flavplot, 1.4237+0.9279)
flavyM<-flavSlope(flavplot, 1.4237+0.1662)

#Calculating predicted values
glucyA<-glucSlope(glucplot, 2.12958)
glucyGM<-glucSlope(glucplot, 2.12958+0.99860)
glucyM<-glucSlope(glucplot, 2.12958+0.08780)


tiff("Defence_Figures/FlavonoidThrips.tiff", units="in", width=8, height=6, res=300)
a<-ggplot(dat[!is.na(dat$flav_Conc),])+
  geom_point(aes(y=ThripsDam,x=flav_Conc,colour=treatment))+theme_simple_multiCol()+
    geom_path(x=flavplot,y=flavyA,size=1.5,colour="#009E73")+
    geom_path(x=flavplot,y=flavyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=flavplot,y=flavyM,size=1.5,colour="#E69F00")+
  scale_y_continuous(breaks=seq(0,70,5))+
  ylab("Thrips Damage")+
    scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
xlab(bquote(bold("[Total Flavonoid] " (mg/ml))))
dev.off()


tiff("Defence_Figures/GlucosinolateThrips.tiff", units="in", width=8, height=6, res=300)
b<-ggplot(dat[!is.na(dat$gluc_Conc),])+
  geom_point(aes(y=ThripsDam,x=gluc_Conc,colour=treatment))+theme_simple_multiCol()+
  geom_path(x=glucplot,y=glucyA,size=1.5,colour="#009E73")+
    geom_path(x=glucplot,y=glucyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=glucplot,y=glucyM,size=1.5,colour="#E69F00")+
    scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  scale_y_continuous(breaks=seq(0,70,5))+
  ylab("Thrips Damage")+
xlab(bquote(bold("[Total Glucosinolate] " (mg/ml))))
dev.off()


c<-ggplot(dat[!is.na(dat$gluc_Conc),])+
  geom_point(aes(y=ThripsDam,x=gluc_Conc,colour=treatment))+theme_simple()+
  geom_path(x=glucplot,y=glucyA,size=1.5,colour="#009E73")+
    geom_path(x=glucplot,y=glucyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=glucplot,y=glucyM,size=1.5,colour="#E69F00")+
    scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  scale_y_continuous(breaks=seq(0,70,5))+
  ylab("Thrips Damage")+
xlab(bquote(bold("[Total Glucosinolate] " (mg/ml))))
dev.off()


library(cowplot)

leg<-get_legend(c)

plot<-plot_grid(a, b,ncol=2,rel_widths = c(1,1),labels = c("a","b"))

y.grob<-textGrob("Thrips Damage",gp=gpar(fontface="bold",fontsize=20),rot=90)


#Mixed plot
library(grid)
library(gridExtra)

tiff("Defence_Figures/Glucosinolate&FlavonoidThrips.tiff", units="in", width=16, height=6, res=300)
grid.arrange(plot,left=y.grob,top=leg)
dev.off()

```



Visualizing with log glucoinolate. 
```{r}
fit_full2<-glmmTMB(ThripsDam~treatment+gluc_Conc+Standardize(GM_Leaf_Area)+Standardize(ChlorA)+(1|Tag),family=nbinom2,data=dat)
summary(fit_full2)


glucSlope=function(x,int,log=F){
  if(log==T){
      y=-2.68407 *x+int
  }
else{
  y=exp(-2.68407 *x+int)
}
    return(y)
}

#Getting x values for prediction. 
glucplot=seq(min(dat$gluc_Conc,na.rm = T),max(dat$gluc_Conc,na.rm=T),length.out = 708)


#Calculating predicted values
glucyA<-glucSlope(glucplot, 0.14105)
glucyGM<-glucSlope(glucplot, 0.14105+0.97745)
glucyM<-glucSlope(glucplot, 0.14105+0.01807)


tiff("Defence_Figures/GlucosinolateThrips2.tiff", units="in", width=8, height=6, res=300)
ggplot(dat[!is.na(dat$gluc_Conc),])+
  geom_point(aes(y=ThripsDam,x=gluc_Conc,colour=treatment))+theme_simple()+
  geom_path(x=glucplot,y=glucyA,size=1.5,colour="#009E73")+
    geom_path(x=glucplot,y=glucyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=glucplot,y=glucyM,size=1.5,colour="#E69F00")+
    scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  ylab("Thrips Damage")+
  scale_y_continuous(breaks=seq(0,70,5))+

xlab(bquote(bold("[Total Glucosinolate] (" ~log(mg/ml)~")")))
dev.off()



#Calculating predicted values
glucyA<-glucSlope(glucplot, 0.14105+1,log=T)
glucyGM<-glucSlope(glucplot, 0.14105+0.97745+1,log=T)
glucyM<-glucSlope(glucplot, 0.14105+0.01807+1,log=T)



tiff("Defence_Figures/LOG_GlucosinolateThrips.tiff", units="in", width=8, height=6, res=300)
ggplot(dat[!is.na(dat$gluc_Conc),])+
  geom_point(aes(y=log(ThripsDam+1),x=gluc_Conc,colour=treatment))+theme_simple_vert()+
  geom_path(x=glucplot,y=glucyA,size=1.5,colour="#009E73")+
    geom_path(x=glucplot,y=glucyGM,size=1.5,colour="#56B4E9")+
  geom_path(x=glucplot,y=glucyM,size=1.5,colour="#E69F00")+
    scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
    ylab(bquote(bold(log("Thrips Damage"+1))))+
xlab(bquote(bold("[Total Glucosinolate] (" ~log(mg/ml)~")")))
dev.off()


```

