---
title: "Fitness In Alone treatment"
author: "Richard Honor"
date: "04/05/2020"
output: html_document
---

#Read in and prep data
```{r}
library(ggplot2)
library(dplyr)
library(lmerTest)
library(car)
library("glmmTMB")


#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")

#Assign family column
prefamily<-gsub("*.\\|","",dat$Tag)
dat$Family<-gsub("\\-.*","",prefamily)

#remove those with fertilizer treatment, and extra genotypes that are only in the alone treatment. 
dat<-dat[!grepl("i",dat$Sample,fixed=T),]


#Function to weigh pathogen damage by leaf area. 
Weigh<-function(x){
  x/(dat$GM_Leaf_Len*dat$GM_Leaf_Wid)
}
#Function to standardize variables. 
Standardize<-function(x){
  standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
}

#Weighing pathogen damage
dat$BlackPathDamW<-Weigh(dat$BlackPathDam)
dat$ThripsDamW<-Weigh(dat$ThripsDam)

#Standardizing pathogen damage (not white pathogen damage, that is logistic)
dat$ThripsDamW<-Standardize(dat$ThripsDamW)
dat$BlackPathDamW<-Standardize(dat$BlackPathDamW)

#Logging pathogen damage data, fern data, and secondary compound and chlorophyll data as they are all skewed. 
dat$BlackPathDamW<-log(dat$BlackPathDamW+abs(min(dat$BlackPathDamW,na.rm=T)+1))
dat$ThripsDamW<-log(dat$ThripsDamW+abs(min(dat$ThripsDamW,na.rm=T)+1))

dat$Fern<-log(dat$Fern+1)
dat$gluc_Conc<-log(dat$gluc_Conc)
dat$flav_Conc<-log(dat$flav_Conc)
dat$ChlorA<-log(dat$ChlorA)

#Creating leaf area vector 
dat$GM_Leaf_Area<-dat$GM_Leaf_Len*dat$GM_Leaf_Wid



#Average Duplicates. 
dat2<-dat %>% select(-X) %>% group_by(Tag) %>%  summarize(gh_col=first(gh_col),gh_bench=first(gh_bench),treatment=first(treatment),GA3=first(GA3),Family=first(Family),Maple_StemHeight_End=mean(Maple_StemHeight_End),Maple_LeafNum_End=mean(Maple_LeafNum_End),maple_leaf_length_0=mean(maple_leaf_length_0),maple_leaves_0=mean(maple_leaves_0),Maple_TotalLeafArea_End=mean(Maple_TotalLeafArea_End),MapleDamage=mean(Maple_Damage_End),Fern=first(Fern),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),maple_height_0=mean(maple_height_0),ChlorA=mean(ChlorA), GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),ThripsDam=mean(ThripsDam),BlackPathDam=mean(BlackPathDam),WhiteFungDam=mean(WhiteFungDam),BlackPathDamW=mean(BlackPathDamW),ThripsDamW=mean(ThripsDamW),GM_Leaf_Area=mean(GM_Leaf_Area))


#Converting white fungal damage to logistic. 
dat2$WhiteFungLogis<-NA
dat2$WhiteFungLogis[dat2$WhiteFungDam>0]<-"Yes"
dat2$WhiteFungLogis[dat2$WhiteFungDam==0]<-"No"


dat2<-dat2[!grepl("maple",dat2$Tag,fixed = T),]

length(unique(dat2$Family))

```



#What predicts garlic mustard performance in the alone treatment? 
```{r}
dat2<-dat2[dat2$treatment=="a",]
#Weighted pathogen damage data are no on too small of a scale. These will be standardized. 


#Modelling random effects 
fit<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|Family)+(1|gh_bench/gh_col),data=dat2)

fit2<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|Family)+(1|gh_bench),data=dat2)

fit3<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|gh_bench/gh_col),data=dat2)

fit4<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|Family),data=dat2)

fit5<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|gh_bench),data=dat2)

#Is collumn important?
anova(fit,fit2) #no it is not.

#Is family important? 
anova(fit,fit5) #nNot at all. 

#Is gh_bench important? 
anova(fit2,fit4) #yes it is



#Modeling fixed effects: 

fit<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|gh_bench),data=dat2)

fit2<-update(fit,~.-ThripsDamW:BlackPathDamW:WhiteFungLogis)
anova(fit,fit2) #Not a significant three way interaction.

fit3<-update(fit2,~.-BlackPathDamW:WhiteFungLogis)
anova(fit3,fit2) #There is not a significant two way interaction, 

fit4<-update(fit3,~.-BlackPathDamW:ThripsDamW)
anova(fit4,fit3)
#There is not a significant interaction between black path dam and thrips dam. 

fit5<-update(fit4,~.-WhiteFungLogis:ThripsDamW)
anova(fit5,fit4) #There is not a significant whitefung dam and thrips dam interaction. 

summary(fit5)#Fern is not significant
fit6<-lmer(GM_TotalLeaf_Area~ThripsDamW+BlackPathDamW+WhiteFungLogis+(1|gh_bench),data=dat2)
summary(fit6)#thrips damage is not significant. 

fit7<-lmer(GM_TotalLeaf_Area~BlackPathDamW+WhiteFungLogis+(1|gh_bench),data=dat2)
summary(fit7)#White fungal damage and black pathogen damage are significant. 



#These coeficients make much more sense, all in the negatives. Weighing was the appropriate thing to do. This should be done in models that predict pathogen response to glucosinolates and flavonoids. - Chlorophyll concentration should be used in those models as well. 
summary(fit7)
hist(residuals(fit7))
plot(residuals(fit7))
plot(fit7)
```

#Is there a cost to glucosinolate production?
```{r}
#Must control for leaf size here. ...
dat2
fit8<-lmer(GM_TotalLeaf_Area~log(BlackPathDam+1)+Standardize(GM_Leaf_Area)+WhiteFungLogis+gluc_Conc+(1|gh_bench),data=dat2)
summary(fit8)
#only black pathogen damage predicts performance in the alone treatment. #No it is not, although... there is a negative slope....

fit8<-lmer(GM_TotalLeaf_Area~log(BlackPathDam+1)+WhiteFungLogis+Standardize(GM_Leaf_Area)+flav_Conc+(1|gh_bench),data=dat2)
summary(fit8) #no although this is now negative as well. This is interesting as it is the opposite of what was observed in the maple treatment. 


```



#Using all individuals from the experiment, *including* those not replicated across treatment. 
```{r}
#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")


#Assign family column
prefamily<-gsub("*.\\|","",dat$Tag)
dat$Family<-gsub("\\-.*","",prefamily)

#remove those with fertilizer treatment only
dat<-dat[!grepl("SMITH1-3-80|MSMID1-2-0|KVEDG1-8-60",dat$Tag),]


#Function to weigh pathogen damage by leaf area. 
Weigh<-function(x){
  x/(dat$GM_Leaf_Len*dat$GM_Leaf_Wid)
}
#Function to standardize variables. 
Standardize<-function(x){
  standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
}

#Weighing pathogen damage
dat$BlackPathDamW<-Weigh(dat$BlackPathDam)
dat$ThripsDamW<-Weigh(dat$ThripsDam)

#Standardizing pathogen damage (not white pathogen damage, that is logistic)
dat$ThripsDamW<-Standardize(dat$ThripsDamW)
dat$BlackPathDamW<-Standardize(dat$BlackPathDamW)

#Logging Data
dat$BlackPathDamW<-log(dat$BlackPathDamW+abs(min(dat$BlackPathDamW,na.rm=T)+1))
dat$ThripsDamW<-log(dat$ThripsDamW+abs(min(dat$ThripsDamW,na.rm=T)+1))

dat$Fern<-log(dat$Fern+1)
dat$gluc_Conc<-log(dat$gluc_Conc)
dat$flav_Conc<-log(dat$flav_Conc)
dat$ChlorA<-log(dat$ChlorA)

#Generating leaf area
dat$GM_Leaf_Area<-dat$GM_Leaf_Len*dat$GM_Leaf_Wid

#Average Duplicates. 
dat2<-dat %>% select(-X) %>% group_by(Tag) %>%  summarize(gh_col=first(gh_col),gh_bench=first(gh_bench),treatment=first(treatment),GA3=first(GA3),Family=first(Family),Maple_StemHeight_End=mean(Maple_StemHeight_End),Maple_LeafNum_End=mean(Maple_LeafNum_End),maple_leaf_length_0=mean(maple_leaf_length_0),maple_leaves_0=mean(maple_leaves_0),Maple_TotalLeafArea_End=mean(Maple_TotalLeafArea_End),MapleDamage=mean(Maple_Damage_End),Fern=first(Fern),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),maple_height_0=mean(maple_height_0),ChlorA=mean(ChlorA), GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),ThripsDam=mean(ThripsDam),BlackPathDam=mean(BlackPathDam),WhiteFungDam=mean(WhiteFungDam),BlackPathDamW=mean(BlackPathDamW),ThripsDamW=mean(ThripsDamW),GM_Leaf_Area=mean(GM_Leaf_Area))


#Converting white fungal damage to logistic. 
dat2$WhiteFungLogis<-NA
dat2$WhiteFungLogis[dat2$WhiteFungDam>0]<-"Yes"
dat2$WhiteFungLogis[dat2$WhiteFungDam==0]<-"No"
```


#Modelling with full data set. 
```{r}
dat2<-dat2[dat2$treatment=="a",]


#Modelling random effects 
fit<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|Family)+(1|gh_bench/gh_col),data=dat2)

fit2<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|Family)+(1|gh_bench),data=dat2)

fit3<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|gh_bench/gh_col),data=dat2)

fit4<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungLogis+(1|Family),data=dat2)


#Is collumn important?
anova(fit,fit2) #no it is not.

#Is family important? 
anova(fit,fit3) #almost, but no it is not

#Is gh_bench important? 
anova(fit2,fit4) #yes it is



#Modeling fixed effects: 

fit<-lmer(GM_TotalLeaf_Area~Fern+ThripsDamW*BlackPathDamW*WhiteFungDam+(1|gh_bench),data=dat2)

fit2<-update(fit,~.-ThripsDamW:BlackPathDamW:WhiteFungDam)
anova(fit,fit2) #Not a significant three way interaction.

fit3<-update(fit2,~.-BlackPathDamW:WhiteFungDam)
anova(fit3,fit2) #There is not a significant two way interaction, 

fit4<-update(fit3,~.-BlackPathDamW:ThripsDamW)
anova(fit4,fit3)
#There is not a significant interaction between black path dam and thrips dam. 

fit5<-update(fit4,~.-WhiteFungDam:ThripsDamW)
anova(fit5,fit4) #There is not a significant whitefung dam and thrips dam interaction. 

summary(fit5)#White Fung Dam is not significant.

fit6<-lmer(GM_TotalLeaf_Area~ThripsDamW+BlackPathDamW+Fern+(1|gh_bench),data=dat2)
summary(fit6)
```

