---
title: "Intraspecific Fitness affect"
author: "Richard Honor"
date: "05/05/2020"
output: html_document
---

#Read in and prep data
```{r}
library(ggplot2)
library(dplyr)
library(lmerTest)
library(car)
library("glmmTMB")


#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")


#remove those with fertilizer treatment, and extra genotypes that are only in the alone treatment. 
dat<-dat[!grepl("i",dat$Sample,fixed=T),]


#Function to standardize data.
Standardize<-function(x,set.sd=F,SD){
  if(set.sd==T){
      standard<-(x-mean(x,na.rm=T))/SD
  }
  else{
     standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
  }
}


dat$Fern<-log(dat$Fern+1)
dat$gluc_Conc<-log(dat$gluc_Conc)
dat$flav_Conc<-log(dat$flav_Conc)
dat$ChlorA<-log(dat$ChlorA)
dat$ThripsDam<-log(dat$ThripsDam+1)
dat$BlackPathDam<-log(dat$BlackPathDam+1)



#Calculating leaf area 
dat$GM_Leaf_Area<-dat$GM_Leaf_Wid*dat$GM_Leaf_Len

#Average Duplicates. 
dat2<-dat %>% select(-X) %>% group_by(Tag) %>%  summarize(gh_col=first(gh_col),gh_bench=first(gh_bench),treatment=first(treatment),GA3=first(GA3),Family=first(Family),Maple_StemHeight_End=mean(Maple_StemHeight_End),Maple_LeafNum_End=mean(Maple_LeafNum_End),maple_leaf_length_0=mean(maple_leaf_length_0),maple_leaves_0=mean(maple_leaves_0),Maple_TotalLeafArea_End=mean(Maple_TotalLeafArea_End),MapleDamage=mean(Maple_Damage_End),Fern=first(Fern),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),maple_height_0=mean(maple_height_0),ChlorA=mean(ChlorA), GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),ThripsDam=mean(ThripsDam),BlackPathDam=mean(BlackPathDam),WhiteFungDam=mean(WhiteFungDam),comp_number=first(comp_number),GM_Leaf_Area=mean(GM_Leaf_Area))


#Converting white fungal damage to logistic. 
dat2$WhiteFungLogis<-NA
dat2$WhiteFungLogis[dat2$WhiteFungDam>0]<-"Yes"
dat2$WhiteFungLogis[dat2$WhiteFungDam==0]<-"No"


dat2<-dat2[!grepl("maple",dat2$Tag,fixed = T),]

dat2<-dat2[dat2$treatment=="gm",]


#All of these genotypes died (15 Genotypes).(We are simply missing a final measurement for e|JBCHY1-1-50|Q|240) That is only 3% Mortality. 
dead<-dat2[is.na(dat2$GM_TotalLeaf_Area),]

#Removing those with dead competitors from the garlic mustard treatment. ("e|JBCHY1-1-50|Q|240") did not die, we are simply missing the final measurement for it.

dead_competitors<-dead %>% filter(treatment=="gm",Tag!="e|JBCHY1-1-50|Q|240") %>% select(comp_number)

#Removing those with dead competitors from the analysis. 
dat2<-dat2 %>% filter(!comp_number %in% dead_competitors$comp_number)
dat<-dat %>% filter(!comp_number %in% dead_competitors$comp_number)
dat2<-dat2[dat2$comp_number!=79,]
dat2<-dat2[dat2$comp_number!=37,]
dat2<-dat2[dat2$comp_number!=59,]

table(dat2$comp_number)
#Generating collumn for the competitor family.
count=0
dat2$Family<-as.character(dat2$Family)
for(i in 1:length(dat2$comp_number)){
  temp<-dat2[dat2$comp_number==dat2$comp_number[i]&dat2$Tag!=dat2$Tag[i],c("Family","GM_TotalLeaf_Area","gluc_Conc")]#Selects the competitors data
count=count+1

  if(length(temp$Family[!is.na(temp$Family)])==0){ #if there are no values...Makes the values NA
   dat2$competitor[i]<-NA
  }
else{ #Assign the competitor data to the data frame. 
    dat2$competitor[i]<-temp$Family[!is.na(temp$Family)] 
}

  if(length(temp$GM_TotalLeaf_Area[!is.na(temp$GM_TotalLeaf_Area)])==0){
   dat2$comp_Size[i]<-NA
  }
else{
   dat2$comp_Size[i]<-temp$GM_TotalLeaf_Area[!is.na(temp$GM_TotalLeaf_Area)]  
}

  if(length(temp$gluc_Conc[!is.na(temp$gluc_Conc)])==0){
   dat2$comp_Gluc[i]<-NA
 }
  else {
  dat2$comp_Gluc[i]<-temp$gluc_Conc[!is.na(temp$gluc_Conc)]
    }
}


```



#What predicts performance in the intraspecific treatment? - no weighed pathogen data
```{r}
#Modelling random effects 

fit<-glmmTMB(GM_TotalLeaf_Area~Fern+BlackPathDam+WhiteFungLogis+(1|Family)+(1|gh_bench),data=dat2)

fit2<-glmmTMB(GM_TotalLeaf_Area~Fern+BlackPathDam+WhiteFungLogis+(1|gh_bench),data=dat2)

fit3<-glmmTMB(GM_TotalLeaf_Area~Fern+BlackPathDam+WhiteFungLogis+(1|Family),data=dat2)

#Is bench important?
anova(fit,fit3) #no it is not.

#Is family important? 
anova(fit,fit2) #Yes it is. 


#Modelling fixed effects 

fit<-glmmTMB(GM_TotalLeaf_Area~Fern+ThripsDam+BlackPathDam+WhiteFungLogis+competitor+comp_Size+(1|Family),data=dat2)

fit2<-update(fit,~.-competitor)
anova(fit,fit2) #competitor not significant predictor. 
summary(fit2)

fit3<-update(fit2,~.-WhiteFungLogis)
anova(fit3,fit2) #White fungal damage not singificant.
summary(fit3)

fit4<-update(fit3,~.-Fern)
anova(fit4,fit3) #Fern not significant
summary(fit4)

#All else is significant. IS gluc_Conc also significant? 

fit5<-glmmTMB(GM_TotalLeaf_Area~ThripsDam+BlackPathDam+comp_Size+comp_Gluc+(1|Family),data=dat2)
summary(fit5) #Glucosinolate is not significant. Therefore, size is significant. is family significant if the effect of size is removed? 


fit5<-glmmTMB(GM_TotalLeaf_Area~ThripsDam+BlackPathDam+competitor+(1|Family),data=dat2)
fit6<-glmmTMB(GM_TotalLeaf_Area~ThripsDam+BlackPathDam+(1|Family),data=dat2)
anova(fit5,fit6) #Even without size included, id of neighbor is not singificant. This is likley because of a lack of sample sie available only in this treament. 


#Best model
fit<-glmmTMB(GM_TotalLeaf_Area~Standardize(comp_Size)+Standardize(ThripsDam)+Standardize(BlackPathDam)+(1|Family),data=dat2[!is.na(dat2$comp_Size),])

fit2<-glmmTMB(GM_TotalLeaf_Area~+Standardize(ThripsDam)+Standardize(BlackPathDam)+(1|Family),data=dat2[!is.na(dat2$comp_Size),])
anova(fit,fit2)
summary(fit)

plot(residuals(fit))
qqnorm(residuals(fit))
plot(residuals(fit,type="pearson"))
plot(residuals(fit,type="pearson")~fitted(fit))


#Coefficients for results
fit<-glmmTMB(Standardize(GM_TotalLeaf_Area,set.sd=T,3549.252)~Standardize(comp_Size)+Standardize(ThripsDam)+Standardize(BlackPathDam)+(1|Family),data=dat2[!is.na(dat2$comp_Size),])
summary(fit)

#-0.31502 effect on SD per SD unit. (GM on GM)

GMonGM<-Standardize(dat2$comp_Size)
GMonGM
#write.csv(GMonGM,"GM_SD_OnGM.csv")
```



#Is there evidence that there is a cost of glucosinolates or flavonoid production in this treatment? 
```{r}
#I must control for leaf size, because there are less glucosinolates with larger leaf sizes. 
fit7<-lmer(GM_TotalLeaf_Area~ BlackPathDam+ WhiteFungLogis+gluc_Conc+GM_Leaf_Area+(1|Family),data=dat2)
summary(fit7) #Not for glucosinolates... significantly positive correlation.

fit7<-lmer(GM_TotalLeaf_Area~BlackPathDam + WhiteFungLogis+flav_Conc+GM_Leaf_Area+(1|Family),data=dat2)
summary(fit7) #Not for flavonoids (Significant postive correlation. )

```



#Calculating genetic correlation between gluc, chlor and total size. 
```{r}

#Standardizing variables
dat2$gluc_ConcS<-Standardize(dat2$gluc_Conc)
dat2$ChlorAS<-Standardize(dat2$ChlorA)
dat2$GM_TotalLeaf_AreaS<-Standardize(dat2$GM_TotalLeaf_Area)

dat2$Family<-as.character(dat2$Family)



datG<-dat2 %>% select(Tag,Family,gluc_ConcS,ChlorAS,GM_TotalLeaf_AreaS,gh_bench) %>%  pivot_longer(c(gluc_ConcS,ChlorAS,GM_TotalLeaf_AreaS))

datG<-dat2 %>% select(Tag,Family,gluc_ConcS,ChlorAS,GM_TotalLeaf_AreaS,gh_bench) %>%  pivot_longer(c(gluc_ConcS,ChlorAS,GM_TotalLeaf_AreaS))


glmmTMB(value ~ -1+name*gh_bench+(-1+name|Family),REML=T,data=datG)
#did not converge... removing bench interaction.

glmmTMB(value ~ -1+name+gh_bench+(-1+name|Family),REML=T,data=datG)
#Did not converge, removing bench. 
glmmTMB(value ~ -1+(-1+name|Family),REML=T,data=datG)
#Still did not converge. 

```