---
title: "Plasticity_Analysis2.0"
author: "Richard Honor"
date: "04/06/2020"
output: html_document
---
#Read in and prep data
```{r}
library(ggplot2)
#library(lme4)
library(lmerTest)
#library(tidyr)
library(cowplot)
library(grid)
library(gridExtra)
library(dplyr)
source("GGPlot_Themes.R")

#read in data
rm(list=ls())
dat<-read.csv("DataSynthesis.csv")

#Remove maple controls data from the data set.
dat<-dat %>% filter(treatment!="mcnt") %>% droplevels()

#remove those with fertilizer treatment, and extra genotypes that are only in the alone treatment. 
dat<-dat[!grepl("i",dat$Sample,fixed=T),]

#Initializing columns to avoid constant error messages. 
dat$WhiteFungLogis<-NA
dat$BlackFungLogis<-NA
```


#Generating data frames with summarized leaf data (dat2) and summarized genotype data (dat3)
```{r}
hist(dat$gluc_Conc)
hist(dat$flav_Conc)
#Both concentrations are above zero. 
min(dat$gluc_Conc,na.rm=T)
min(dat$flav_Conc,na.rm=T)


#Logging data
dat$Fern<-log(dat$Fern+1)
dat$gluc_Conc<-log(dat$gluc_Conc)
dat$flav_Conc<-log(dat$flav_Conc)
dat$ChlorA<-log(dat$ChlorA)
dat$ThripsDam<-log(dat$ThripsDam+1)
dat$BlackPathDam<-log(dat$BlackPathDam+1)
dat$Fern<-log(dat$Fern+1)



#Creating leaf area vector 
dat$GM_Leaf_Area<-dat$GM_Leaf_Len*dat$GM_Leaf_Wid


#Summarizing: Taking the mean value of leaves. This tibble contains data at the level of the plant means. 
dat2<-dat %>% group_by(Tag) %>% summarize(ChlorA=mean(ChlorA),ChlorB=mean(ChlorB),gluc_Conc=mean(gluc_Conc),flav_Conc=mean(flav_Conc),Family=first(Family),treatment=first(treatment),gh_row=first(gh_row),gh_bench=first(gh_bench),GM_TotalLeaf_Area=first(GM_TotalLeaf_Area),comp_number=first(comp_number),ThripsDam=mean(ThripsDam),WhiteFungDam=mean(WhiteFungDam),BlackPathDam=mean(BlackPathDam),Fern=mean(Fern),gh_col=first(gh_col),GM_Leaf_Area=mean(GM_Leaf_Area),Latitude=first(Latitude),Longitude=first(Longitude),Altitude=first(Altitude))
dat

#All of these genotypes died (15 Genotypes).(We are simply missing a final measurement for e|JBCHY1-1-50|Q|240) That is only 3% Mortality. 
dead<-dat2[is.na(dat2$GM_TotalLeaf_Area),]

#Removing those with dead competitors from the garlic mustard treatment. ("e|JBCHY1-1-50|Q|240") did not die, we are simply missing the final measurement for it.

dead_competitors<-dead %>% filter(treatment=="gm",Tag!="e|JBCHY1-1-50|Q|240") %>% select(comp_number)

#Removing those with dead competitors from the analysis. 
dat2<-dat2 %>% filter(!comp_number %in% dead_competitors$comp_number)
dat<-dat %>% filter(!comp_number %in% dead_competitors$comp_number)


##Summarizing: Taking the mean value of plants. This tibble contains data at the level of the family means within each treatment. 
#dat3<-dat2 %>% drop_na(GM_TotalLeaf_Area) %>% group_by(Family,treatment)  %>% summarize_if(is.numeric,mean)



#Because of how zero inflated white pathogen damage is, i will use a logistic regression to model it.
dat2$WhiteFungLogis<-NA
dat2$WhiteFungLogis[dat2$WhiteFungDam==0]<-0
dat2$WhiteFungLogis[dat2$WhiteFungDam>0]<-1


  #Function to standardize variables. 
Standardize<-function(x){
  standard<-(x-mean(x,na.rm=T))/sd(x,na.rm=T)
}

#Standardizing leaf area. 
dat2$GM_Leaf_Area<-Standardize(dat2$GM_Leaf_Area)
```


#Glucosinolate plastsicity
```{r}
library(glmmTMB)
#Maximum model
fit<-glmmTMB(gluc_Conc~treatment+GM_Leaf_Area+(1|Family)+(1|gh_bench),data=dat2)
fit2<-glmmTMB(gluc_Conc~treatment+GM_Leaf_Area+(1|Family),data=dat2)
fit3<-glmmTMB(gluc_Conc~treatment+GM_Leaf_Area+(1|gh_bench),data=dat2)

anova(fit,fit2) #Greenhouse bench is not
anova(fit3,fit) #Family and Tag is very significant. 

fit<-glmmTMB(gluc_Conc~treatment+Standardize(GM_Leaf_Area)+(1|Family),data=dat2)
fit4<-glmmTMB(gluc_Conc~Standardize(GM_Leaf_Area)+(1|Family),data=dat2)
anova(fit,fit4)
summary(fit)
confint(fit)

#"Active plasticity" Eventhough it could still be passive after accounting for chlorophyll
fit<-glmmTMB(gluc_Conc~treatment+Standardize(GM_Leaf_Area)+Standardize(ChlorA)+(1|Family),data=dat2)
fit2<-glmmTMB(gluc_Conc~Standardize(GM_Leaf_Area)+Standardize(ChlorA)+(1|Family),data=dat2)
anova(fit,fit2)
confint(fit)

summary(fit) #Treatment is still significant, however, the magnitude of the significance is much reduced, i think that it is sharing the significance with chlorophyll. 
```

#Visualization of Apparent treatment means glucosinolate
```{r}
source("GGPlot_Themes.R")

#Visualizing passive plasticity
a<--1.55899177
gm<--1.55899177-0.16618664
m<--1.55899177-0.18518751
Vis<-data.frame(
  treatment=c("Alone","Garlic Mustard","Maple"),estimate=c(a,gm,m),upper=c(-1.50051001,a-0.09022637,a-0.11887264),lower=c(-1.61747353,a-0.24214691,a-0.25150238 ))


Gpassive<-ggplot(Vis,aes(x = treatment, 
                    y = estimate, colour = treatment))+
  geom_point(size = 5)+
  geom_errorbar(ymin = Vis$lower,
                ymax = Vis$upper, width = 0.1)+
  scale_x_discrete(name="",labels=c("Alone","Intraspecific","Interspecific"))+
  scale_y_continuous(limits = c(-1.9,-1.4), name = bquote(bold("[Glucosinolate] (log" (mg/mL)~")")),breaks=seq(-1.9,-1.4,by=0.1))+
  scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  theme_simple_multiCol()+theme(
    axis.title.y =  element_text(color = "black", size = 16, face = "bold",margin=margin(3,20,3,0),angle = 90),
  )

a<--1.63713694
gm<--1.63713694-0.06113577
m<--1.63713694-0.07089345
Vis<-data.frame(
  treatment=c("Alone","Garlic Mustard","Maple"),estimate=c(a,gm,m),upper=c(-1.585805632,a-0.005747620,a-0.021957509),lower=c(-1.68846825,a-0.11652391,a-0.11982939 ))

#Visualizing Active plasticity
Gactive<-ggplot(Vis,aes(x = treatment, 
                    y = estimate, colour = treatment))+
  geom_point(size = 5)+
  geom_errorbar(ymin = Vis$lower,
                ymax = Vis$upper, width = 0.1)+
  scale_x_discrete(name="",labels=c("Alone","Intraspecific","Interspecific"))+
  scale_y_continuous(limits = c(-1.9,-1.4),breaks=seq(-1.9,-1.4,by=0.1))+
  scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  theme_simple_multiCol()

tiff("Plasticity_Figures/Glucosinolate_Plasticity.tiff", units="in", width=12, height=6, res=300)
plot_grid(passive,active,labels = c("a","b"),rel_widths = c(1.1,1))
dev.off()
```

#Flavonoid plasticity
```{r}
library(glmmTMB)
#Maximum model
#Convergence problem forced to use replication at family level, not individual level
fit<-glmmTMB(flav_Conc~treatment+Standardize(GM_Leaf_Area)+(1|Family)+(1|gh_bench),data=dat2)
fit2<-glmmTMB(flav_Conc~treatment+Standardize(GM_Leaf_Area)+(1|Family),data=dat2) 
fit3<-glmmTMB(flav_Conc~treatment+Standardize(GM_Leaf_Area)+(1|gh_bench),data=dat2) #Convergence problem

anova(fit,fit2) #Greenhouse bench is significant

anova(fit3,fit) #Family is not significant at all. No genetic variation for family.

summary(fit3)
confint(fit3)

#"Active plasticity" Eventhough it could still be passive after accounting for chlorophyll
fit<-glmmTMB(flav_Conc~treatment+Standardize(GM_Leaf_Area)+Standardize(ChlorA)+(1|Family),data=dat2)

fit2<-glmmTMB(flav_Conc~Standardize(GM_Leaf_Area)+Standardize(ChlorA)+(1|Family),data=dat2)
summary(fit2)

anova(fit,fit2) #Treatment is not significant with flavonoids after accounting for chlorophyll. 
summary(fit)
confint(fit)

```

#Visualization of treatment means flavonoid
```{r}
#Visualizing passive plasticity
a<--2.21675805
gm<--2.21675805-0.20969999
m<--2.21675805-0.10422161
Vis<-data.frame(
  treatment=c("Alone","Garlic Mustard","Maple"),estimate=c(a,gm,m),upper=c(-2.11846559,a-0.12720992,a-0.03237505),lower=c(-2.31505050,a-0.29219007,a-0.17606816 ))


Fpassive<-ggplot(Vis,aes(x = treatment, 
                    y = estimate, colour = treatment))+
  geom_point(size = 5)+
  geom_errorbar(ymin = Vis$lower,
                ymax = Vis$upper, width = 0.1)+
  scale_x_discrete(name="",labels=c("Alone","Intraspecific","Interspecific"))+
  scale_y_continuous(limits = c(-2.6,-2), name = bquote(bold("[Flavonoid] (log" (mg/mL)~")")),breaks=seq(-2.6,-2,by=0.1))+
  scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  theme_simple_multiCol()+theme(
    axis.title.y =  element_text(color = "black", size = 16, face = "bold",margin=margin(3,20,3,0),angle = 90),
  )



#Visualizing active plasticity
a<--2.26994454
gm<--2.26994454-0.08570059
m<--2.26994454-0.01716435
Vis<-data.frame(
  treatment=c("Alone","Garlic Mustard","Maple"),estimate=c(a,gm,m),upper=c(-2.2211349151,a-0.0123743864,a+0.0487751134),lower=c(-2.3187541572,a-0.1590268033,a-0.0831038233 ))


Factive<-ggplot(Vis,aes(x = treatment, 
                    y = estimate, colour = treatment))+
  geom_point(size = 5)+
  geom_errorbar(ymin = Vis$lower,
                ymax = Vis$upper, width = 0.1)+
  scale_x_discrete(name="",labels=c("Alone","Intraspecific","Interspecific"))+
  scale_y_continuous(limits = c(-2.6,-2), name = bquote(bold("[Flavonoid] (log" (mg/mL)~")")),breaks=seq(-2.6,-2,by=0.1))+
  scale_colour_manual(values=c("#009E73","#56B4E9","#E69F00"),labels=c("Alone","Garlic Mustard","Maple"))+
  theme_simple_multiCol()

tiff("Plasticity_Figures/Flavonoid_Plasticity.tiff", units="in", width=12, height=6, res=300)
plot_grid(Fpassive,Factive,labels = c("a","b"),rel_widths = c(1.1,1))
dev.off

```

#four panel plot
```{r}

tiff("Plasticity_Figures/FlavGluc_Plasticity.tiff", units="in", width=12, height=10, res=300)

plot_grid(Gpassive,Gactive,Fpassive,Factive,labels = c("a","b","c","d"),align = "hv",label_fontfamily = "Arial",label_size = 18)

dev.off()

```













#Visualizing correlation between gluc, flav and chlorophyll. 
```{r}
source("GGPlot_Themes.R")
library(cowplot)
library(gridExtra)




flav<-ggplot(dat)+
  geom_point(aes(y=flav_Conc,x=ChlorA))+
  ylab(bquote(bold("[Flavonoid] (log"*(mg/ml)*")")))+
  xlab(bquote(bold("[Chlorophyll A] (log"*(μg/ml)*")")))+
  geom_abline(slope=0.3939,intercept = -1.8336,size=1)+
  scale_y_continuous(breaks = seq(-4,1,0.25))+
  scale_x_continuous(breaks = seq(-4,1,0.5))+
  theme_simple_vert()
flav

gluc<-ggplot(dat)+
  geom_point(aes(y=gluc_Conc,x=ChlorA))+
  ylab(bquote(bold("[Glucosinolate] (log"*(mg/ml)*")")))+
  xlab(bquote(bold("[Chlorophyll A] (log"*(μg/ml)*")")))+
    geom_abline(slope=0.45340,intercept = -1.14540,size=1 )+
   scale_y_continuous(breaks = seq(-4,0,0.25))+
  scale_x_continuous(breaks = seq(-4,1,0.5))+
  theme_simple_vert()
gluc

flavfit<-lm(flav_Conc~ChlorA,data=dat)
glucfit<-lm(gluc_Conc~ChlorA,data=dat)

summary(flavfit)
summary(glucfit)

tiff("Other_Figures/Log_GlucFlavChlor_Cor.tiff", units="in", width=12, height=6, res=300)
plot_grid(gluc,flav,ncol=2,nrow=1,labels=c("a","b"),label_fontfamily = "Arial",label_size = 18)
dev.off()


```



